#ifndef FETCH_MEM_H
#define FETCH_MEM_H
#include <stdint.h>
#include <string.h>
#include <ap_int.h>
#include "hls_snap_1024.H"
#include <action_memcopy.h> /* Memcopy Job definition */
#include "hw_action_hbm.H"


void read_ocapi_to_stream (hls::stream<snap_membus_512_t>& wide_stream,
                        snap_membus_512_t *din_gmem,
                        snapu64_t input_address,
                        snapu64_t size_in_lines);
void membus_to_HBMbus_compatible_stream(hls::stream<snap_membus_256_t>& out_stream, hls::stream<snap_membus_512_t>& wide_stream,
                             snapu64_t wide_lines);
void write_HBM_stream(hls::stream<snap_membus_256_t>& out_stream, 
            snap_membus_256_t *d_hbm_p0,
            snap_membus_256_t *d_hbm_p1,
            snap_membus_256_t *d_hbm_p2,
            snap_membus_256_t *d_hbm_p3,
            snap_membus_256_t *d_hbm_p4,
            snap_membus_256_t *d_hbm_p5,
            snap_membus_256_t *d_hbm_p6,
            snap_membus_256_t *d_hbm_p7,
            snap_membus_256_t *d_hbm_p8,
            snap_membus_256_t *d_hbm_p9,
            snap_membus_256_t *d_hbm_p10,
            snap_membus_256_t *d_hbm_p11,
            snap_membus_256_t *d_hbm_p12,
            snap_membus_256_t *d_hbm_p13,
            snap_membus_256_t *d_hbm_p14,
            snap_membus_256_t *d_hbm_p15,
            snap_membus_256_t *d_hbm_p16,
             snap_membus_256_t *d_hbm_p17,
             snap_membus_256_t *d_hbm_p18,
             snap_membus_256_t *d_hbm_p19,
             snap_membus_256_t *d_hbm_p20,
             snap_membus_256_t *d_hbm_p21,
             snap_membus_256_t *d_hbm_p22,
             snap_membus_256_t *d_hbm_p23,
             snap_membus_256_t *d_hbm_p24,
             snap_membus_256_t *d_hbm_p25,
             snap_membus_256_t *d_hbm_p26,
             snap_membus_256_t *d_hbm_p27,
             snap_membus_256_t *d_hbm_p28,
             snap_membus_256_t *d_hbm_p29,
             snap_membus_256_t *d_hbm_p30,
             snap_membus_256_t *d_hbm_p31,
             
            snapu64_t output_address,
            snapu64_t lines_transfer,
            unsigned parallel_factor);

void hbm_stream_splitter (
   hls::stream<snap_membus_256_t>& bus_input,
   hls::stream<snap_membus_256_t> output[MANY_ACC],
   unsigned num_input_lines);
void write_HBM_stream_parallel(hls::stream<snap_membus_256_t>hbm_write_stream[MANY_ACC], 
            snap_membus_256_t *d_hbm_p0,
            snap_membus_256_t *d_hbm_p1,
            snap_membus_256_t *d_hbm_p2,
            snap_membus_256_t *d_hbm_p3,
            snap_membus_256_t *d_hbm_p4,
            snap_membus_256_t *d_hbm_p5,
            snap_membus_256_t *d_hbm_p6,
            snap_membus_256_t *d_hbm_p7,
            snap_membus_256_t *d_hbm_p8,
            snap_membus_256_t *d_hbm_p9,
            snap_membus_256_t *d_hbm_p10,
            snap_membus_256_t *d_hbm_p11,
            snap_membus_256_t *d_hbm_p12,
            snap_membus_256_t *d_hbm_p13,
            snap_membus_256_t *d_hbm_p14,
            snap_membus_256_t *d_hbm_p15,
            snap_membus_256_t *d_hbm_p16,
         snap_membus_256_t *d_hbm_p17,
         snap_membus_256_t *d_hbm_p18,
         snap_membus_256_t *d_hbm_p19,
         snap_membus_256_t *d_hbm_p20,
         snap_membus_256_t *d_hbm_p21,
         snap_membus_256_t *d_hbm_p22,
         snap_membus_256_t *d_hbm_p23,
         snap_membus_256_t *d_hbm_p24,
         snap_membus_256_t *d_hbm_p25,
         snap_membus_256_t *d_hbm_p26,
         snap_membus_256_t *d_hbm_p27,
         snap_membus_256_t *d_hbm_p28,
         snap_membus_256_t *d_hbm_p29,
         snap_membus_256_t *d_hbm_p30,
         snap_membus_256_t *d_hbm_p31,
             
            snapu64_t output_address,
            snapu64_t lines_transfer);

void fetch_mem(snap_membus_512_t *din_gmem,
                  snap_membus_256_t *d_hbm_p0,
                  snap_membus_256_t *d_hbm_p1,
            snap_membus_256_t *d_hbm_p2,
            snap_membus_256_t *d_hbm_p3,
            snap_membus_256_t *d_hbm_p4,
            snap_membus_256_t *d_hbm_p5,
            snap_membus_256_t *d_hbm_p6,
            snap_membus_256_t *d_hbm_p7,
            snap_membus_256_t *d_hbm_p8,
            snap_membus_256_t *d_hbm_p9,
            snap_membus_256_t *d_hbm_p10,
            snap_membus_256_t *d_hbm_p11,
            snap_membus_256_t *d_hbm_p12,
            snap_membus_256_t *d_hbm_p13,
            snap_membus_256_t *d_hbm_p14,
            snap_membus_256_t *d_hbm_p15,
            snap_membus_256_t *d_hbm_p16,
         snap_membus_256_t *d_hbm_p17,
         snap_membus_256_t *d_hbm_p18,
         snap_membus_256_t *d_hbm_p19,
         snap_membus_256_t *d_hbm_p20,
         snap_membus_256_t *d_hbm_p21,
         snap_membus_256_t *d_hbm_p22,
         snap_membus_256_t *d_hbm_p23,
         snap_membus_256_t *d_hbm_p24,
         snap_membus_256_t *d_hbm_p25,
         snap_membus_256_t *d_hbm_p26,
         snap_membus_256_t *d_hbm_p27,
         snap_membus_256_t *d_hbm_p28,
         snap_membus_256_t *d_hbm_p29,
         snap_membus_256_t *d_hbm_p30,
         snap_membus_256_t *d_hbm_p31,
                  snapu64_t input_address,snapu64_t output_address,
                  snapu64_t lines_transfer);



#endif